# -*- coding: utf-8 -*-
"""Convert jpn/cards.json descriptions to Korean using term map + pattern fixes."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ENG = ROOT / "TheQueen/localization/eng/cards.json"
JPN = ROOT / "TheQueen/localization/jpn/cards.json"
KOR_OUT = ROOT / "TheQueen/localization/kor/cards.json"
TITLES_SRC = Path(__file__).with_name("build_kor_cards.py")

# Order: longer phrases first
TERM_REPLACEMENTS = [
    ("[gold]意図学習[/gold]", "[gold]의도 학습[/gold]"),
    ("意図学習", "의도 학습"),
    ("[purple]魂縛[/purple]", "[purple]영혼 속박[/purple]"),
    ("魂縛", "영혼 속박"),
    ("[gold]融合体[/gold]", "[gold]융합체[/gold]"),
    ("融合体", "융합체"),
    ("[gold]魂灯[/gold]", "[gold]영혼등[/gold]"),
    ("魂灯", "영혼등"),
    ("[aqua]魂灯", "[aqua]영혼등"),
    ("[gold]フェード[/gold]", "[gold]페이드[/gold]"),
    ("フェード", "페이드"),
    ("[gold]リプレイ[/gold]", "[gold]재사용[/gold]"),
    ("リプレイ", "재사용"),
    ("[gold]保留[/gold]", "[gold]보유[/gold]"),
    ("保留", "보유"),
    ("[gold]ブロック[/gold]", "[gold]방어도[/gold]"),
    ("ブロック", "방어도"),
    ("[gold]筋力[/gold]", "[gold]힘[/gold]"),
    ("筋力", "힘"),
    ("[gold]敏捷[/gold]", "[gold]민첩[/gold]"),
    ("敏捷", "민첩"),
    ("[gold]脆弱[/gold]", "[gold]취약[/gold]"),
    ("脆弱", "취약"),
    ("[gold]弱体[/gold]", "[gold]약화[/gold]"),
    ("弱体", "약화"),
    ("[gold]毒[/gold]", "[gold]독[/gold]"),
    ("[gold]破滅[/gold]", "[gold]종말[/gold]"),
    ("[gold]崩御[/gold]", "[gold]종언[/gold]"),
    ("[gold]消耗[/gold]", "[gold]소멸[/gold]"),
    ("消耗", "소멸"),
    ("[gold]エセリアル[/gold]", "[gold]천상[/gold]"),
    ("エセリアル", "천상"),
    ("[gold]無形[/gold]", "[gold]무형[/gold]"),
    ("無形", "무형"),
    ("[gold]召喚[/gold]", "[gold]소환[/gold]"),
    ("召喚", "소환"),
    ("[gold]手札[/gold]", "[gold]손[/gold]"),
    ("手札", "손"),
    ("[gold]消耗札[/gold]", "[gold]소멸 더미[/gold]"),
    ("消耗札", "소멸 더미"),
    ("[gold]山札[/gold]", "[gold]뽑을 더미[/gold]"),
    ("山札", "뽑을 더미"),
    ("[gold]捨て札[/gold]", "[gold]버림 더미[/gold]"),
    ("捨て札", "버림 더미"),
    ("[gold]複合[/gold]", "[gold]복합[/gold]"),
    ("複合", "복합"),
    ("[gold]捕獲[/gold]", "[gold]포획[/gold]"),
    ("捕獲", "포획"),
    ("[gold]モンスターカード[/gold]", "[gold]몬스터 카드[/gold]"),
    ("モンスターカード", "몬스터 카드"),
    ("[gold]忘却[/gold]", "[gold]잊음[/gold]"),
    ("忘却", "잊음"),
    ("[gold]学習[/gold]", "[gold]학습[/gold]"),
    ("[gold]フレイル[/gold]", "[gold]손상[/gold]"),
    ("フレイル", "손상"),
    ("[gold]プレート[/gold]", "[gold]판금[/gold]"),
    ("プレート", "판금"),
    ("[gold]締め付け[/gold]", "[gold]조이기[/gold]"),
    ("[gold]トゲ[/gold]", "[gold]가시[/gold]"),
    ("トゲ", "가시"),
    ("[gold]儀式[/gold]", "[gold]의식[/gold]"),
    ("[gold]城壁[/gold]", "[gold]방벽[/gold]"),
    ("[gold]ガルバニック[/gold]", "[gold]전류[/gold]"),
    ("[gold]飛翔[/gold]", "[gold]날아오르기[/gold]"),
    ("[gold]ゴールド[/gold]", "[gold]금[/gold]"),
    ("ゴールド", "금"),
    ("[gold]リーサル[/gold]", "[gold]치명[/gold]"),
    ("リーサル", "치명"),
    ("[gold]ボス[/gold]", "[gold]보스[/gold]"),
    ("[gold]スキル[/gold]", "[gold]스킬[/gold]"),
    ("[gold]攻撃[/gold]", "[gold]공격[/gold]"),
    ("[gold]パワー[/gold]", "[gold]능력[/gold]"),
    ("付与：", "부여:"),
    ("付与:", "부여:"),
    ("Enchant:", "부여:"),
    ("腐食", "부식"),
    ("[purple]萎凋", "[purple]고갈"),
    ("萎凋", "고갈"),
    ("[purple]目眩[/purple]", "[purple]멍함[/purple]"),
    ("目眩", "멍함"),
    ("[purple]スライム[/purple]", "[purple]점액[/purple]"),
    ("スライム", "점액"),
    ("[purple]燃焼[/purple]", "[purple]화상[/purple]"),
    ("燃焼", "화상"),
    ("[purple]寄生[/purple]", "[purple]감염[/purple]"),
    ("寄生", "감염"),
    ("[purple]毒性[/purple]", "[purple]독성[/purple]"),
    ("[gold]防御型[/gold]", "[gold]방어형[/gold]"),
    ("[gold]攻撃型[/gold]", "[gold]공격형[/gold]"),
    ("[gold]デッキに加えない[/gold]", "[gold]덱에 추가되지 않음[/gold]"),
    ("デッキに加えない", "덱에 추가되지 않음"),
    ("[gold]複合-進化[/gold]", "[gold]복합-진화[/gold]"),
    ("すべての敵", "모든 적"),
    ("すべての", "모든 "),
    ("ランダムな", "무작위 "),
    ("ランダムに", "무작위로 "),
    ("ランダムで", "무작위로 "),
    ("カードを", "카드를 "),
    ("カード", "카드"),
    ("枚引く", "장을 뽑습니다"),
    ("枚", "장"),
    ("ターン", "턴"),
    ("を生成する", "을 생성합니다"),
    ("を生成", "을 생성"),
    ("を得る", "을 얻습니다"),
    ("を失う", "을 잃습니다"),
    ("を付与する", "을 부여합니다"),
    ("を付与", "을 부여"),
    ("をプレイ", "을 냅"),
    ("プレイ", "냅"),
    ("対象", "대상"),
    ("敵", "적"),
    ("ターン開始時", "턴 시작 시"),
    ("ターン終了時", "턴 종료 시"),
    ("次のターン", "다음 턴"),
    ("このターン", "이번 턴"),
    ("戦闘終了時", "전투 종료 시"),
    ("戦闘", "전투"),
    ("取得時", "획득 시"),
    ("捨てる", "버립"),
    ("選択", "선택"),
    ("選ぶ", "선택하세요"),
    ("選んで", "선택해"),
    ("選び", "선택"),
    ("除去", "제거"),
    ("永続的に", "영구"),
    ("即座に", "즉시"),
    ("連続", "연속"),
    ("回", "번"),
    ("ヒット", "타격"),
    ("デバフ", "디버프"),
    ("行動", "행동"),
    ("睡眠", "수면"),
    ("逃走", "도주"),
    ("離脱", "떠납"),
    ("盗む", "훔칩"),
    ("固定", "고정"),
    ("倍", "배"),
    ("以下", "이하"),
    ("以上", "이상"),
    ("通常", "일반"),
    ("エリート", "정예"),
    ("味方", "팀원"),
    ("プレイヤー", "플레이어"),
    ("山札から", "뽑을 더미에서"),
    ("捨て札から", "버림 더미에서"),
    ("消耗札から", "소멸 더미에서"),
    ("手札に加える", "손에 추가"),
    ("手札に戻す", "손으로 되돌립"),
    ("手札から", "손에서"),
    ("手札の", "손의"),
    ("手札", "손"),
    ("アップグレード", "강화"),
    ("ダウングレード", "강화 해제"),
    ("コスト", "비용"),
    ("増加", "증가"),
    ("減少", "감소"),
    ("変化", "변화"),
    ("変身", "변환"),
    ("生成", "생성"),
    ("与える", "줍니다"),
    ("得る", "얻"),
    ("失う", "잃"),
]

CARD_NAME_JP_KR = [
    ("ソウルストライク+", "영혼 타격+"),
    ("ソウルストライク", "영혼 타격"),
    ("ソウル防御+", "영혼 방어+"),
    ("ソウル防御", "영혼 방어"),
    ("貫通充填+", "관통 충전+"),
    ("貫通充填", "관통 충전"),
    ("拡散充填+", "확散 충전+"),
    ("拡散充填", "확산 충전"),
    ("第一詠唱", "첫 주문"),
    ("第二詠唱", "둘째 주문"),
    ("最終詠唱", "마지막 주문"),
    ("継続意図", "의도 계속"),
    ("放棄意図", "의도 포기"),
    ("恐怖の覚醒+", "공포 각성+"),
    ("恐怖の覚醒", "공포 각성"),
    ("苦痛の覚醒+", "고통 각성+"),
    ("苦痛の覚醒", "고통 각성"),
    ("引っかき", "할퀴기"),
    ("貪食+", "삼키기+"),
    ("貪食", "삼키기"),
    ("富と名声+", "명예와 부+"),
    ("富と名声", "명예와 부"),
    ("長寿+", "장수+"),
    ("長寿", "장수"),
    ("山の力+", "산의 힘+"),
    ("山の力", "산의 힘"),
    ("掌握の手+", "포획의 손+"),
    ("掌握の手", "포획의 손"),
    ("拒絶の手+", "거부의 손+"),
    ("拒絶の手", "거부의 손"),
    ("骨の給餌+", "뼈 먹이+"),
    ("骨の給餌", "뼈 먹이"),
    ("肉の給餌+", "살 먹이+"),
    ("肉の給餌", "살 먹이"),
    ("明星", "새벽별"),
    ("夕星", "저녁별"),
    ("タックル+", "쓰러뜨리기+"),
    ("タックル", "쓰러뜨리기"),
    ("金切り声", "비명"),
    ("力の舞", "힘의 춤"),
    ("招き", "손짓"),
    ("在庫", "비축"),
    ("妨害", "분산"),
    ("叩きつけ", "내려치기"),
    ("委任", "위임"),
    ("引き継ぎ", "장악"),
    ("入れ替え", "측면 전환"),
    ("入場券+", "입장권+"),
    ("入場券", "입장권"),
    ("硬い卵", "단단한 알"),
    ("軽い噛み", "갉아먹기"),
    ("狂乱の引きずり", "격렬한 당김"),
    ("若返り", "회춘"),
    ("心の明晰", "정신 명료"),
    ("崩壊", "분해"),
    ("呪詛", "저주"),
    ("激怒", "격노"),
    ("痛烈な刺突", "고통스러운 찌르기"),
    ("個人の巣", "개인 벌집"),
    ("扉番の殻", "문지기 껍질"),
    ("生命の火花", "활력의 불꽃"),
    ("絡みつき", "얽힘"),
    ("スモッグ", "연무"),
    ("爆発", "폭발"),
    ("砂穴", "모래함정"),
    ("背後攻撃", "등 뒤 공격"),
    ("カードの出所", "카드 출처"),
    ("カード 출처", "카드 출처"),
    ("硬化した殻", "경화 껍질"),
    ("殺しにくさ", "죽기 어려움"),
    ("不均衡", "불균형"),
    ("潜り", "땅굴"),
    ("滑り", "미끄러움"),
    ("窃盗", "절도"),
    ("吸収", "흡수"),
    ("憑依", "얽매기"),
    ("飢え", "굶주림"),
    ("臆病", "겁 많음"),
    ("丸まる", "웅크리기"),
    ("柔らかさ", "연화"),
    ("蒸気噴出", "증기 분출"),
    ("縮小光線", "축소 광선"),
    ("尖刺", "가시 돋이기"),
    ("突出した棘", "돌출 가시"),
    ("禁忌の詠唱", "금단의 주문"),
    ("甲虫の突進", "딱정벌레 돌진"),
    ("一斉射撃", "난사"),
    ("粘液嘔吐", "이코 토하기"),
    ("衰弱の霧", "쇠약의 연기"),
    ("瘴気", "독무"),
    ("殴り合い", "주먹 대결"),
    ("頭突き", "박치기"),
    ("噛みつき", "물기"),
    ("毒の唾", "독 침"),
    ("転がり出し", "구르기"),
    ("挟み撃ち", "집게"),
    ("ひったくり", "훔치기"),
    ("魂吸収", "영혼 흡수"),
    ("火炎放射", "화염방사"),
    ("フレイル", "도리깨"),
    ("眷属よ！集結せよ！", "친족들! 집합!"),
    ("エナジーオーブ", "에너지 구슬"),
    ("獣の咆哮", "야수의 울부짖음"),
    ("鎮魂の棺", "영혼 안정 관"),
    ("血搾り", "피 짜내기"),
    ("自爆", "자폭"),
    ("解放", "해방"),
    ("マリオネット", "인형"),
    ("狂乱の噛みつき", "광란의 물기"),
    ("処刑", "처형"),
    ("迅速適応", "빠른 적응"),
    ("宣言", "선언"),
    ("回し蹴り", "회전차기"),
    ("製造", "조립"),
    ("幻影", "환상"),
    ("幻影 II", "환상 II"),
    ("ガード", "경비"),
    ("ノイズ", "소음"),
    ("刺突", "찌르기"),
    ("ザップ", "전격"),
    ("粘液", "점액"),
    ("毒性", "독성"),
    ("粘着射撃", "끈적한 사격"),
    ("よこせ！", "내놔"),
    ("グレムリンの刺突", "그렘린 찌르기"),
    ("戦術指令", "전술 지령"),
    ("空間裂き", "공간 찢기"),
    ("時間の戯れ", "시간 속임수"),
    ("紙切れ", "종이 베기"),
    ("宝物殿", "보물 전각"),
    ("魔法の顔料", "마법 안료"),
    ("捕食同化", "포식적 동화"),
    ("蠢動", "꿈틀거림"),
    ("鞭打ち", "채찍"),
    ("再接続", "재부착"),
    ("実験体", "실험체"),
    ("生命吸収", "생명 흡수"),
    ("フェロモン噴射", "페로몬 침"),
    ("扉を閉じる", "문 닫기"),
    ("再装填", "재장전 사격"),
    ("絡みつく蔓", "휘감는 덩굴"),
    ("高度なガス", "고급 가스"),
    ("産卵", "알 낳기"),
    ("蟹の激怒", "게의 분노"),
    ("地面液化", "땅 액화"),
    ("ギャラリー開館", "갤러리 개장"),
    ("統合失調", "분열"),
]

# Manual overrides for keys where auto-conversion is poor
OVERRIDES = {
    "COMICCHESS-BOUNDED.description": "[purple]영혼 속박[/purple]",
    "THE_QUEEN_CARD_GEM_FLAME.description": "피해를 {Damage:diff()} 줍니다. 이 카드를 [purple]영혼 속박[/purple]으로 부식합니다.",
    "THE_QUEEN_CARD_BIND_CARD.description": "[gold]손[/gold]의 카드 1장을 [purple]영혼 속박[/purple]으로 부식합니다.",
    "THE_QUEEN_CARD_BIND_CARD.selectionPrompt": "[purple]영혼 속박[/purple]으로 부식할 [gold]손[/gold]의 카드 1장을 선택하세요.",
    "THE_QUEEN_CARD_GUARD.description": "[gold]방어형[/gold].\n[gold]의도 학습[/gold]: [gold]방어도[/gold] {LearnIntentBlock:diff()}을 얻습니다.",
    "THE_QUEEN_CARD_RELOAD_FIRE.description": "{Summon:diff()} [gold]소환[/gold]합니다.\n[gold]의도 학습[/gold]: [gold]방어도[/gold] {LearnIntentBlock:diff()}을 얻습니다. 다음 턴 시작 시, {LearnIntentDamage:diff()} 피해를 줍니다.",
    "THE_QUEEN_CARD_SWITCH_SIDE.description": "모든 적의 [gold]등 뒤 공격[/gold]을 전환합니다: {InCombat:{IsLeft:choose(0):[gold]융합체[/gold]|당신}|당신 또는 [gold]융합체[/gold]}에게 받는 피해가 [blue]50%[/blue] 증가합니다.",
    "THE_QUEEN_CARD_BEAST_CRY.description": "{Summon:diff()} [gold]소환[/gold]합니다.\n[gold]의도 학습[/gold]: 모든 적을 1턴 [gold]기절[/gold]시킵니다. 2턴 동안 잠듭니다.",
    "THE_QUEEN_CARD_CLAMP.description": "{Summon:diff()} [gold]소환[/gold]합니다.\n[gold]의도 학습[/gold]: {LearnIntentDamage:diff()} 피해를 2번 줍니다.\n[gold]의도 학습[/gold]: 카드 {LearnIntentDraw}장을 뽑고 부여: [purple]멍함[/purple].",
    "THE_QUEEN_CARD_TREASURE_PAVILION.selectionPrompt": "[gold]버림 더미[/gold]에서 영혼 속박이 없는 카드 1장을 선택하세요.",
    "THE_QUEEN_CARD_ADMISSION_TICKET.description": "{InCombat:[gold]손[/gold]에서 카드 1장을 선택해 [gold]{Applier}[/gold]에게 줍니다.|[gold]손[/gold]에서 카드 1장을 선택해 [gold]카드 출처[/gold]에게 줍니다.}",
    "THE_QUEEN_CARD_LIQUIFY_GROUND.description": "{Sandpit:choose(0):[gold]모래함정[/gold] {AmalgamSandpitPower:diff()}을 얻습니다.\n|}{InCombat:|보스 전투면, 대신 10을 얻습니다.\n}{Summon:diff()} [gold]소환[/gold]합니다.\n[gold]의도 학습[/gold]: [gold]격렬한 당김[/gold] 1장을 생성합니다.",
    "THE_QUEEN_CARD_FRANTIC_TUG.description": "[gold]모래함정[/gold] 카운트가 -1됩니다.\n이 카드 비용이 +1됩니다.",
    "THE_QUEEN_CARD_RAID.description": "턴 시작 시, [gold]{IfUpgraded:show:쓰러뜨리기+|쓰러뜨리기}[/gold] 1장을 생성합니다.",
    "THE_QUEEN_CARD_SPIKEN.description": "{Summon:diff()} [gold]소환[/gold]합니다.\n[gold]의도 학습[/gold]: [gold]가시[/gold] 3을 얻습니다.",
    "THE_QUEEN_CARD_PHEROMONE_SPIT.description": "{Summon:diff()} [gold]소환[/gold]합니다.\n[gold]의도 학습[/gold]: [gold]개인 벌집[/gold] 1과 [gold]힘[/gold] 1을 얻습니다.\n[purple]영혼 속박[/purple]",
    "THE_QUEEN_CARD_HARD_TO_KILL.description": "[gold]융합체[/gold]가 [gold]죽기 어려움[/gold] 9을 얻습니다. 1턴 지속.\n[gold]소멸[/gold].",
    "THE_QUEEN_CARD_BEETLE_CHARGE.description": "[gold]융합체[/gold] 체력이 [blue]50%[/blue] 이하일 때만 낼 수 있습니다.\n[gold]융합체[/gold]가 {LearnIntentDamage:diff()} 피해를 줍니다.",
    "THE_QUEEN_CARD_YOU_ARE_MINE.description": "{Hits:diff()}번 연속으로, 무작위 적에게 [gold]취약[/gold] 또는 [gold]약화[/gold] 1을 부여합니다.",
    "THE_QUEEN_CARD_FIRST_CHANT.description": "[gold]손[/gold]의 [gold]둘째 주문[/gold]에 [gold]재사용[/gold] 1을 부여합니다. 이 카드를 [gold]손[/gold]으로 되돌립니다.",
    "THE_QUEEN_CARD_SECOND_CHANT.description": "[gold]손[/gold]의 [gold]마지막 주문[/gold] 타격 횟수를 1 증가시킵니다. 이 카드를 [gold]손[/gold]으로 되돌립니다.",
    "THE_QUEEN_CARD_ROAR_CLAW.description": "{Summon:diff()} [gold]소환[/gold]합니다.\n[gold]융합체[/gold]가 [gold]취약[/gold] {LearnIntentVulnerable:diff()}을 부여합니다.\n[gold]의도 학습[/gold]: {LearnIntentDamage:diff()} 피해를 2번 줍니다.",
    "THE_QUEEN_CARD_DOUBLE_BLAST.description": "{Summon:diff()} [gold]소환[/gold]합니다.\n[gold]의도 학습[/gold]: {LearnIntentDamage:diff()} 피해를 줍니다. [gold]힘[/gold] {LearnIntentStrength:diff()}을 얻습니다.\n[gold]의도 학습[/gold]: {LearnIntentDamage2:diff()} 피해를 2번 줍니다.",
    "THE_QUEEN_CARD_PUNCH_OFF.description": "{Summon:diff()} [gold]소환[/gold]합니다.\n[gold]의도 학습[/gold]: [gold]방어도[/gold] {LearnIntentBlock:diff()}을 얻습니다.\n[gold]의도 학습[/gold]: {LearnIntentDamage:diff()} 피해를 2번 줍니다. [gold]약화[/gold] {LearnIntentWeak:diff()}을 부여합니다.",
    "THE_QUEEN_CARD_FLAIL.description": "{Summon:diff()} [gold]소환[/gold]합니다.\n[gold]의도 학습[/gold]: {LearnIntentDamage:diff()} 피해를 2번 줍니다.",
    "THE_QUEEN_CARD_SPINNING_KICK.description": "{Summon:diff()} [gold]소환[/gold]합니다.\n[gold]의도 학습[/gold]: {LearnIntentDamage:diff()} 피해를 4번 줍니다.",
    "THE_QUEEN_CARD_LASH.description": "{Summon:diff()} [gold]소환[/gold]합니다.\n[gold]의도 학습[/gold]: {LearnIntentDamage:diff()} 피해를 4번 줍니다. 이 카드는 [purple]감염[/purple]을 여러 번 부여할 수 있습니다.",
    "THE_QUEEN_CARD_ILLUSION2.description": "{Summon:diff()} [gold]소환[/gold]합니다.\n[gold]의도 학습[/gold]: [gold]내려치기[/gold] 1장을 [gold]손[/gold]에 추가합니다.",
    "THE_QUEEN_CARD_FABRICATE.description": "{Summon:diff()} [gold]소환[/gold]합니다.\n[gold]의도 학습[/gold]: [gold]방어형[/gold] 로봇 카드 1장과 [gold]공격형[/gold] 로봇 카드 1장을 생성합니다.",
    "THE_QUEEN_CARD_GREMLIN_STAB.description": "[gold]융합체[/gold]가 대상에게 {Damage:diff()} 피해를 줍니다. [gold]금[/gold] {Gold:diff()}을 훔칩니다.",
}


def load_titles():
    ns = {"__file__": str(TITLES_SRC), "Path": Path}
    exec(TITLES_SRC.read_text(encoding="utf-8"), ns)
    return ns["TITLES"]


def convert_text(text: str) -> str:
    for jp, kr in CARD_NAME_JP_KR:
        text = text.replace(f"[gold]{jp}[/gold]", f"[gold]{kr}[/gold]")
    for old, new in TERM_REPLACEMENTS:
        text = text.replace(old, new)
    # damage patterns
    text = re.sub(r"\{([^}]+)\}ダメージを与える", r"피해를 {\1} 줍니다", text)
    text = re.sub(r"\{([^}]+)\}ダメージ", r"{\1} 피해", text)
    text = re.sub(r"(\{[^}]+\}) \[gold]ブロック\[/gold]を得る", r"[gold]방어도[/gold]를 \1 얻습니다", text)
    text = re.sub(r"(\{[^}]+\}) \[gold]筋力\[/gold]を得る", r"[gold]힘[/gold] \1을 얻습니다", text)
    text = text.replace("ダメージを与える", "피해를 줍니다")
    text = text.replace("を得る。", "을 얻습니다.")
    text = text.replace("を得る", "을 얻습니다")
    text = text.replace("。", ".")
    return text


def main():
    eng = json.loads(ENG.read_text(encoding="utf-8-sig"))
    jpn = json.loads(JPN.read_text(encoding="utf-8"))
    titles = load_titles()

    kor = {}
    for key, eng_val in eng.items():
        if key.endswith(".title"):
            kor[key] = titles[key]
        elif key in OVERRIDES:
            kor[key] = OVERRIDES[key]
        else:
            src = jpn.get(key, eng_val)
            kor[key] = convert_text(src)

    assert len(kor) == 444
    assert set(kor) == set(eng)
    KOR_OUT.parent.mkdir(parents=True, exist_ok=True)
    KOR_OUT.write_text(json.dumps(kor, ensure_ascii=False, indent=4) + "\n", encoding="utf-8")
    print(f"Wrote {KOR_OUT} ({len(kor)} keys)")


if __name__ == "__main__":
    main()
